services:
  database:
    image: postgres:15.2-bullseye
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5439:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: